site_name: 'Real-Time Simulation Modeling for Digital Twins'
site_url: 'https://bulentsoykan.github.io/real-time-simulation-book'
site_author: 'Bulent Soykan'
site_description: 'A graduate-level textbook on developing Digital Twins using core simulation modeling paradigms.'

# Repository information for 'Edit this page' and repository links
repo_url: 'https://github.com/bulentsoykan/real-time-simulation-book.git'
repo_name: 'View on GitHub'
edit_uri: 'edit/main/docs/' # Assumes your Markdown files are in the 'docs' folder on the 'main' branch

# ----------------------------------------------------------------------------
# Theme Configuration (using Material for MkDocs)
# ----------------------------------------------------------------------------
theme:
  name: material
  language: en
  # Features for enhanced navigation and user experience
  features:
    - navigation.instant # Speeds up page loads for a seamless experience
    - navigation.tabs # Use top-level nav sections as tabs
    - navigation.sections # Expands navigation for the current section
    - navigation.top # Adds a "Back to top" button
    - search.suggest # Autocomplete search suggestions
    - search.highlight # Highlights search terms on the results page
    - content.code.copy # Adds a "copy to clipboard" button to all code blocks
    - content.code.annotate # Allows for line-by-line code explanations

  # Color palette with a light/dark mode toggle
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: 'blue'
      accent: 'blue'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Fonts (optional, the defaults are excellent)
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

  # Logo and favicon
  favicon: 'assets/favicon.png'
  logo: 'assets/logo.svg' 

# ----------------------------------------------------------------------------
# Markdown Extensions for Technical Content
# ----------------------------------------------------------------------------
markdown_extensions:
  - admonition # Special colored blocks for notes, warnings, tips (e.g., !!! note)
  - pymdownx.details # Collapsible content blocks
  - pymdownx.superfences # Allows nesting code blocks in lists, etc.
  - pymdownx.tabbed: # Creates tabbed content areas
      alternate_style: true
  - pymdownx.emoji: # Use emojis like :+1:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight: # Advanced syntax highlighting
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # Highlight code within text: `#!python var = 1`
  - pymdownx.arithmatex: # For LaTeX mathematical notation
      generic: true
  - toc: # Table of Contents generation
      permalink: true # Adds a clickable anchor link to all headings
      toc_depth: 3

# ----------------------------------------------------------------------------
# Plugins
# ----------------------------------------------------------------------------
plugins:
  - search # Built-in search plugin, enabled by default
  # - mkdocs-pdf-export # Example: Uncomment and 'pip install' to enable PDF export

# ----------------------------------------------------------------------------
# Custom JavaScript for MathJax (for rendering LaTeX)
# ----------------------------------------------------------------------------
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# ----------------------------------------------------------------------------
# Navigation Structure (The Table of Contents)
# This directly maps to your 15-chapter textbook outline.
# The file paths assume you create subdirectories inside your 'docs' folder
# for each part to keep the project organized.
# ----------------------------------------------------------------------------
nav:
  - 'Home': 'index.md'
  - 'Part I: Foundations of Digital Twins and Simulation':
    - 'Chapter 1: The Digital Twin Paradigm': 'part1/chapter01.md'
    - 'Chapter 2: Simulation as the Core Engine': 'part1/chapter02.md'
    - 'Chapter 3: A Methodological Survey': 'part1/chapter03.md'
  - 'Part II: Core Simulation Modeling Techniques':
    - 'Chapter 4: Discrete-Event Simulation': 'part2/chapter04.md'
    - 'Chapter 5: Agent-Based Modeling': 'part2/chapter05.md'
    - 'Chapter 6: System Dynamics': 'part2/chapter06.md'
    - 'Chapter 7: Dynamical Systems & Physics-Based Modeling': 'part2/chapter07.md'
  - 'Part III: Enabling Real-Time Twining and Synthesis':
    - 'Chapter 8: Real-Time Data Ingestion': 'part3/chapter08.md'
    - 'Chapter 9: State Synchronization': 'part3/chapter09.md'
    - 'Chapter 10: Hybrid Simulation': 'part3/chapter10.md'
  - 'Part IV: Validation, Analysis, and Advanced Applications':
    - 'Chapter 11: Continuous Validation & UQ': 'part4/chapter11.md'
    - 'Chapter 12: Predictive Analysis & What-If': 'part4/chapter12.md'
    - 'Chapter 13: Optimization and Control': 'part4/chapter13.md'
  - 'Part V: Deployment and Future Directions':
    - 'Chapter 14: Architectures and Platforms': 'part5/chapter14.md'
    - 'Chapter 15: The Future of Simulation-Powered DTs': 'part5/chapter15.md'
  - 'Appendix':
    - 'Glossary': 'appendix/glossary.md'
    - 'Software Setup Guide': 'appendix/setup.md'